### PR TITLE
refactor schemas for new linking scheme

### PR DESCRIPTION
**Pull request by pfrazee**
https://github.com/ssbc/secure-scuttlebutt/issues/94

### CODE REVIEW

**Comment by pfrazee** [comment]
The new schemas I'm proposing for this update:

``` js
{
  type: 'post',
  text: string,
  repliesTo: {msg:},
  refers: [{msg:}],
  mentions: [{feed:}],
  attachments: [{ext:}]
}
{ type: 'advert', text: string }
{ type: 'name', name: string }
{ type: 'name', name: string, target: {feed:} }
{ type: 'follow', follow: bool, target: {feed:} }
{ type: 'trust', trust: -1|0|1, target: {feed:} }
{ type: 'pub', address: string }
```

**Comment by pfrazee** [comment]
Using a generic rel like `target` is nice for the messages themselves, not particularly useful for the indexes. For instance, `feedsLinkedToFeed({ id: bob.id, rel: 'target' })`. We either need the link targets to incorporate the message's type (eg `feedsLinkedToFeed({ id: bob.id, type: 'follow', rel: 'target' })`) or the rel should be non-generic, eg `{ type: 'follow', follow: {feed:}, value: bool }`

**Comment by dominictarr** [comment]
the "replies to" name should be consistent with https://github.com/ssbc/secure-scuttlebutt/pull/96
I vote using `repliesTo`.

**Comment by pfrazee** [comment]
+1 on repliesTo. Should rels be case-sensitive? In all my uses so far, I look for `content.repliesTo`, which means it is. However, I have `ssb-msgs` lowercase the rels it emits to make it case-insensitive. Im not totally sure ti works to do both.

Also, what are your thoughts on the 'target' rel?

**Comment by pfrazee** [comment]
How might mynosql impact this `target` reltype issue?

Here's what I'd go with if not using the `target` reltype:

```
{ type: 'name', name: string }
{ type: 'name', name: string, names: {feed:} }
{ type: 'follow', retract: bool, follows: {feed:} }
{ type: 'trust', rating: -1|0|1, trusts: {feed:} }
{ type: 'pub', address: string }
```

**Comment by dominictarr** [comment]
@pfraze hmm, if we are gonna use a single `target` link, what if we just collapse the name/follow/trust types into one type?

**Comment by pfrazee** [comment]
something like...

```
{ type: 'assign', name: string, trust: -1|0|1, following: bool, target: { feed: } }
```

?

**Comment by dominictarr** [comment]
assign isn't the right word, it's about a relationship between two people...
what about "relation"... hmm, is there something better?

**Comment by pfrazee** [comment]
how about 'contact', as in an entry in an address book? I also propose we use a more descriptive rel for this, maybe:

```
{ type: 'contact', contact: { feed: }, name: string, trust: -1|0|1, following: bool }
```

thus we get

``` js
feedsLinkedToFeed({ id: bob.id, rel: 'contact' })
```

**Comment by pfrazee** [comment]
If we do combine into one message type, would we want to include all of the current data in each message?

If somebody were interacting with phoenix, it would be...

```
{ type: 'contact', contact: { feed: $hash }, following: true }
{ type: 'contact', contact: { feed: $hash }, name: 'bob' }
{ type: 'contact', contact: { feed: $hash }, trust: 1 }
```

vs

```
{ type: 'contact', contact: { feed: $hash }, following: true, trust: 0 }
{ type: 'contact', contact: { feed: $hash }, following: true, name: 'bob', trust: 0 }
{ type: 'contact', contact: { feed: $hash }, following: true, name: 'bob', trust: 1 }
```

The latter would be handy since we could just fetch the most recent message to get the current state

**Comment by pfrazee** [comment]
Would we want to change the self-name message to be something like `type: profile` instead of `type: name` so that it can bundle other information?

**Comment by dominictarr** [comment]
no I think merge the messages, it's not a big deal.
yeah 'contact' is okay.

**Comment by pfrazee** [comment]
published `2.0.0`

**Pull request merged**
